/**
 * MODULE BÁO CÁO — Seed template từ file Chốt.BM_TongHop_ChienDich_LaiXeMoToAnToan.
 * Chỉ là dữ liệu mẫu rút gọn field chính; admin có thể clone/sửa trên UI.
 * Gọi API: POST /api/bao-cao/templates/seed-bm
 */
function buildBmLaiXeMoToTemplate() {
  const num = (key, label, groupKey, order, unit = "") => ({
    key,
    label,
    groupKey,
    dataType: "number",
    required: false,
    order,
    unit,
    aggregatable: true,
    formula: "",
    visibleForRoles: [],
  });

  const text = (key, label, groupKey, order) => ({
    key,
    label,
    groupKey,
    dataType: "text",
    required: false,
    order,
    unit: "",
    aggregatable: false,
    formula: "",
    visibleForRoles: [],
  });

  const date = (key, label, groupKey, order) => ({
    key,
    label,
    groupKey,
    dataType: "date",
    required: false,
    order,
    unit: "",
    aggregatable: false,
    formula: "",
    visibleForRoles: [],
  });

  const bool = (key, label, groupKey, order) => ({
    key,
    label,
    groupKey,
    dataType: "boolean",
    required: false,
    order,
    unit: "",
    aggregatable: true,
    formula: "",
    visibleForRoles: [],
  });

  return {
    ten: "BM Tổng hợp Chiến dịch lái xe mô tô, xe gắn máy an toàn",
    mota: "Biểu mẫu chuẩn theo file Chốt BM_TongHop — có thể clone và chỉnh field.",
    version: 1,
    nguon: "local",
    coHangTongCong: true,
    metaFields: [
      {
        key: "don_vi_tong_hop",
        label: "Đơn vị báo cáo (cấp tổng hợp)",
        dataType: "text",
        options: [],
        required: false,
        order: 1,
      },
      {
        key: "loai_bao_cao",
        label: "Loại báo cáo",
        dataType: "select",
        options: ["Tháng", "Quý", "Đợt"],
        required: false,
        order: 2,
      },
      {
        key: "can_bo_tong_hop",
        label: "Cán bộ tổng hợp",
        dataType: "text",
        options: [],
        required: false,
        order: 3,
      },
      {
        key: "so_dien_thoai",
        label: "Số điện thoại",
        dataType: "text",
        options: [],
        required: false,
        order: 4,
      },
    ],
    sections: [
      {
        key: "bieu1_tham_muu",
        title: "Biểu 1: Tham mưu, triển khai, tập huấn",
        sheetName: "1.THAM MUU-TRIEN KHAI",
        order: 1,
        groups: [
          { key: "tham_muu", title: "Tham mưu, ban hành văn bản", order: 1 },
          { key: "trien_khai", title: "Triển khai đến cơ sở", order: 2 },
          { key: "tap_huan", title: "Tập huấn lực lượng nòng cốt", order: 3 },
          { key: "phoi_hop", title: "Phối hợp", order: 4 },
        ],
        fields: [
          num("so_vb_tham_muu", "Số văn bản tham mưu cấp ủy, chính quyền", "tham_muu", 1, "Văn bản"),
          bool("ubnd_ban_hanh_kh", "UBND đã ban hành Kế hoạch (1=có)", "tham_muu", 2),
          date("ngay_ubnd_ban_hanh", "Ngày UBND ban hành Kế hoạch", "tham_muu", 3),
          num("so_kh_don_vi", "Số Kế hoạch/văn bản của đơn vị đã ban hành", "tham_muu", 4, "Văn bản"),
          num("tong_xa_phuong", "Tổng số xã, phường trên địa bàn", "trien_khai", 5, "Xã, phường"),
          num("so_xa_phuong_trien_khai", "Số xã, phường đã ban hành kế hoạch", "trien_khai", 6, "Xã, phường"),
          num("so_lop_tap_huan", "Số lớp tập huấn báo cáo viên, hướng dẫn viên", "tap_huan", 7, "Lớp"),
          num("so_bcv_tap_huan", "Số báo cáo viên đã tập huấn", "tap_huan", 8, "Người"),
          num("so_tieu_giao_vien", "Số tiểu giáo viên cấp cơ sở đã lập danh sách", "tap_huan", 9, "Người"),
          num("so_cbcs_csgt_tap_huan", "Số CBCS là CSGT được tập huấn", "tap_huan", 10, "Người"),
          num("so_cbcs_cax_tap_huan", "Số CBCS là Công an xã được tập huấn", "tap_huan", 11, "Người"),
          num("so_so_ban_nganh_phoi_hop", "Số sở, ban, ngành, đoàn thể phối hợp", "phoi_hop", 12),
          num("so_truong_thpt_phoi_hop", "Số trường học THPT phối hợp", "phoi_hop", 13),
        ],
      },
      {
        key: "bieu2_doi_tuong",
        title: "Biểu 2: Đối tượng cần đào tạo / đã đào tạo",
        sheetName: "2.DOI TUONG DAO TAO",
        order: 2,
        groups: [
          { key: "can_dao_tao", title: "A. Số đối tượng cần đào tạo", order: 1 },
          { key: "da_dao_tao", title: "B. Số đối tượng đã được đào tạo", order: 2 },
        ],
        fields: [
          num("can_dt_khu_dan_cu", "Cần ĐT: Người dân khu dân cư", "can_dao_tao", 1, "Người"),
          num("can_dt_gplx_30_50", "Cần ĐT: GPLX mô tô 30–50 tuổi", "can_dao_tao", 2, "Người"),
          num("can_dt_hs_thpt", "Cần ĐT: Học sinh THPT/GDNN", "can_dao_tao", 3, "Người"),
          num("can_dt_sinh_vien", "Cần ĐT: Sinh viên", "can_dao_tao", 4, "Người"),
          num("da_dt_khu_dan_cu", "Đã ĐT: Người dân khu dân cư", "da_dao_tao", 5, "Người"),
          num("da_dt_gplx_30_50", "Đã ĐT: GPLX mô tô 30–50 tuổi", "da_dao_tao", 6, "Người"),
          num("da_dt_hs_thpt", "Đã ĐT: Học sinh THPT/GDNN", "da_dao_tao", 7, "Người"),
          num("da_dt_sinh_vien", "Đã ĐT: Sinh viên", "da_dao_tao", 8, "Người"),
          num("da_dt_cong_nhan", "Đã ĐT: Công nhân, NLĐ KCN", "da_dao_tao", 9, "Người"),
        ],
      },
      {
        key: "bieu3_tuyen_truyen",
        title: "Biểu 3: Tuyên truyền, giáo dục pháp luật TTATGT",
        sheetName: "3.TUYEN TRUYEN",
        order: 3,
        groups: [
          { key: "truc_tiep", title: "Tuyên truyền trực tiếp", order: 1 },
          { key: "truyen_thong", title: "Truyền thông, trực quan", order: 2 },
        ],
        fields: [
          num("tt_khu_dan_cu", "Buổi TT tại khu dân cư", "truc_tiep", 1, "Buổi"),
          num("tt_truong_hoc", "Buổi TT tại trường học", "truc_tiep", 2, "Buổi"),
          num("tt_co_quan", "Buổi TT tại cơ quan, DN, KCN", "truc_tiep", 3, "Buổi"),
          num("tong_buoi_tt", "Tổng số buổi tuyên truyền", "truc_tiep", 4, "Buổi"),
          num("tong_luot_nguoi_tt", "Tổng số lượt người được tuyên truyền", "truc_tiep", 5, "Người"),
          num("so_tin_bai_mxh", "Số tin, bài trên mạng xã hội", "truyen_thong", 6),
          num("so_luot_tiep_can", "Số lượt tiếp cận nền tảng số", "truyen_thong", 7),
          num("so_to_roi", "Số tờ rơi, tài liệu đã phát", "truyen_thong", 8),
          num("so_cam_ket", "Số bản cam kết đã ký", "truyen_thong", 9),
        ],
      },
      {
        key: "bieu4_dao_tao_kn",
        title: "Biểu 4: Đào tạo kỹ năng lái xe an toàn",
        sheetName: "4.DAO TAO KY NANG",
        order: 4,
        groups: [
          { key: "buoi", title: "SỐ BUỔI ĐÀO TẠO KỸ NĂNG", order: 1 },
          { key: "nguoi", title: "SỐ NGƯỜI THAM GIA", order: 2 },
          { key: "danh_gia", title: "KIỂM TRA, ĐÁNH GIÁ", order: 3 },
          { key: "dieu_kien", title: "ĐIỀU KIỆN BẢO ĐẢM", order: 4 },
        ],
        fields: [
          num("buoi_sa_hinh_du", "Sa hình đầy đủ 11 tình huống", "buoi", 1, "Buổi"),
          num("buoi_sa_hinh_rut", "Sa hình rút gọn (chóp nón, tình huống cơ bản)", "buoi", 2, "Buổi"),
          num("buoi_thuc_te", "Thực hành trên tuyến đường thực tế", "buoi", 3, "Buổi"),
          num("tong_buoi_dao_tao", "TỔNG SỐ BUỔI", "buoi", 4, "Buổi"),
          num("tong_nguoi_dao_tao", "Tổng số người được đào tạo kỹ năng", "nguoi", 5, "Người"),
          num("dt_hoc_sinh_sv", "Trong đó: học sinh, sinh viên", "nguoi", 6, "Người"),
          num("dt_cong_nhan", "Trong đó: công nhân, người lao động", "nguoi", 7, "Người"),
          num("dt_gplx_30_50", "Trong đó: người có GPLX từ 30-50 tuổi", "nguoi", 8, "Người"),
          num("so_kiem_tra", "Số người được kiểm tra, đánh giá", "nguoi", 9, "Người"),
          num("so_dat_truoc", "Số đạt TRƯỚC đào tạo", "danh_gia", 10, "Người"),
          num("ty_le_dat_truoc", "Tỷ lệ đạt trước đào tạo (%)", "danh_gia", 11, "%"),
          num("so_dat_sau", "Số đạt SAU đào tạo", "danh_gia", 12, "Người"),
          num("ty_le_dat_sau", "Tỷ lệ đạt sau đào tạo (%)", "danh_gia", 13, "%"),
          num("muc_chuyen_bien", "Mức chuyển biến (sau - trước)", "danh_gia", 14, "%"),
          num("so_luot_cbcs_hd", "Số lượt CBCS tham gia hướng dẫn", "danh_gia", 15, "Lượt"),
          num("so_hdv_co_so", "Số hướng dẫn viên cơ sở tham gia", "dieu_kien", 16, "Người"),
          num("so_pt_huy_dong", "Số phương tiện huy động thực hành", "dieu_kien", 17, "Xe"),
          num("so_san_bai_sa_hinh", "Số sân, bãi, sa hình đã bố trí", "dieu_kien", 18, "Địa điểm"),
        ],
      },
      {
        key: "bieu5_xu_ly_vp",
        title: "Biểu 5: Tuần tra, xử lý vi phạm mô tô",
        sheetName: "5.XU LY VI PHAM MO TO",
        order: 5,
        groups: [
          { key: "chung", title: "Kết quả chung", order: 1 },
          { key: "hanh_vi", title: "Phân tích theo hành vi", order: 2 },
        ],
        fields: [
          num("tong_xu_ly", "Tổng số trường hợp xử lý", "chung", 1),
          num("so_tien_phat", "Số tiền phạt (đồng)", "chung", 2, "Đồng"),
          num("tam_giu_pt", "Tạm giữ phương tiện", "chung", 3),
          num("tuoc_gplx", "Tước quyền sử dụng GPLX", "chung", 4),
          num("tru_diem_gplx", "Trừ điểm GPLX", "chung", 5),
          num("vp_nong_do_con", "Nồng độ cồn", "hanh_vi", 6),
          num("vp_toc_do", "Vi phạm tốc độ", "hanh_vi", 7),
          num("vp_khong_gplx", "Không có GPLX / không hợp lệ", "hanh_vi", 8),
          num("vp_khong_mu", "Không đội mũ bảo hiểm", "hanh_vi", 9),
        ],
      },
      {
        key: "bieu6_tngt",
        title: "Biểu 6: TNGT liên quan mô tô, xe gắn máy",
        sheetName: "6.TNGT MO TO",
        order: 6,
        groups: [
          { key: "trong_ky", title: "Trong kỳ báo cáo", order: 1 },
          { key: "thang_truoc", title: "Tháng trước liền kề", order: 2 },
        ],
        fields: [
          num("tngt_so_vu", "Số vụ TNGT", "trong_ky", 1, "Vụ"),
          num("tngt_chet", "Số người chết", "trong_ky", 2, "Người"),
          num("tngt_bi_thuong", "Số người bị thương", "trong_ky", 3, "Người"),
          num("tngt_so_vu_truoc", "Số vụ (tháng trước)", "thang_truoc", 4, "Vụ"),
          num("tngt_chet_truoc", "Số người chết (tháng trước)", "thang_truoc", 5, "Người"),
          num("tngt_bi_thuong_truoc", "Số người bị thương (tháng trước)", "thang_truoc", 6, "Người"),
        ],
      },
      {
        key: "bieu7_kho_khan",
        title: "Biểu 7: Khó khăn, đề xuất",
        sheetName: "7.KHO KHAN-DE XUAT",
        order: 7,
        groups: [{ key: "nd", title: "Nội dung", order: 1 }],
        fields: [
          text("nhom_noi_dung", "Nhóm nội dung", "nd", 1),
          text("kho_khan", "Khó khăn, vướng mắc cụ thể", "nd", 2),
          text("nguyen_nhan", "Nguyên nhân", "nd", 3),
          text("de_xuat", "Đề xuất, kiến nghị", "nd", 4),
          text("cap_giai_quyet", "Cấp giải quyết", "nd", 5),
          text("muc_do_uu_tien", "Mức độ ưu tiên", "nd", 6),
          text("ghi_chu", "Ghi chú", "nd", 7),
        ],
      },
    ],
    summaryItems: [
      { label: "Số văn bản tham mưu", mode: "field", sourceFieldKey: "so_vb_tham_muu", formula: "", unit: "Văn bản", order: 1 },
      { label: "Số lớp tập huấn", mode: "field", sourceFieldKey: "so_lop_tap_huan", formula: "", unit: "Lớp", order: 2 },
      { label: "Tổng lượt người tuyên truyền", mode: "field", sourceFieldKey: "tong_luot_nguoi_tt", formula: "", unit: "Người", order: 3 },
      { label: "Tổng người đào tạo kỹ năng", mode: "field", sourceFieldKey: "tong_nguoi_dao_tao", formula: "", unit: "Người", order: 4 },
      { label: "Tổng xử lý vi phạm", mode: "field", sourceFieldKey: "tong_xu_ly", formula: "", unit: "Trường hợp", order: 5 },
      { label: "TNGT số vụ", mode: "field", sourceFieldKey: "tngt_so_vu", formula: "", unit: "Vụ", order: 6 },
    ],
  };
}

module.exports = { buildBmLaiXeMoToTemplate };
